IF NOT EXISTS (SELECT * FROM sys.databases WHERE name='DemoDb')
    BEGIN
        CREATE DATABASE DemoDb
    END
;

CREATE TABLE Employees (
    Id INTEGER PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(500) NULL,
    Salary INTEGER DEFAULT 0
)
GO

